### ISSUE TITLE
[BUG] Extending the default theme gives a trix error

### ISSUE THREAD

**Issue by grantholle** [laraform/laraform#28]
### Prerequisites

* [x] Able to reproduce the behaviour outside of your code, the problem is isolated to Laraform.
* [x] Provided all the required dependencies to reproduce the bug (eg. form, component, model, migration).
* [x] Your issue isn't already filed.
* [x] You filled in the entire issue template.

### Versions

* PHP version: 7.3.8
* Laravel version: 6.6.1
* Laraform Vue package version: 1.1.8
* Laraform Laravel package version: 1.1.8

### Description

When trying to create a custom theme that extends the default theme, there's an error referring to trix.

### Steps to Reproduce

My theme file, `themes/tailwind.js`:

```js
import utils from '@laraform/laraform/src/utils'
import defaultTheme from '@laraform/laraform/src/themes/default'

export default utils.extendTheme(defaultTheme, {
  classes: {},
  elements: {},
  components: {},
  layouts: {},
  grid: {},
})
```

app.js

```js
import Tailwind from './themes/tailwind'

Laraform.theme('tailwind', Tailwind)

Laraform.config({
  theme: 'tailwind',

  endpoints: {
    process: '/laraform/process',

    // Only required for full version
    elements: {
      trix: {
        attachment: '/laraform/trix-attachment'
      }
    },
    validators: {
      active_url: '/laraform/validator/active_url',
      exists: '/laraform/validator/exists',
      unique: '/laraform/validator/unique',
    },
  }
})

Vue.use(Laraform)
```

**Expected behavior:**

The theme will compile successfully with all the appropriate elements.

**Actual behavior:** 

The app does not render and the console shows:

```
app.js:77732 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "trix-toolbar" has already been used with this registry
    at http://localhost:8080//js/app.js:77732:28411
    at Object../node_modules/trix/dist/trix.js.e.registerElement (http://localhost:8080//js/app.js:77732:26899)
    at Object.<anonymous> (http://localhost:8080//js/app.js:77733:13468)
    at Object.<anonymous> (http://localhost:8080//js/app.js:77733:13887)
    at Object.<anonymous> (http://localhost:8080//js/app.js:77738:25376)
    at Object.<anonymous> (http://localhost:8080//js/app.js:77742:103)
    at Object../node_modules/trix/dist/trix.js (http://localhost:8080//js/app.js:77743:30)
    at __webpack_require__ (http://localhost:8080//js/app.js:770:30)
    at fn (http://localhost:8080//js/app.js:130:20)
    at Module../node_modules/vue-loader/lib/index.js?!./node_modules/@laraform/laraform/src/components/wrappers/Trix.vue?vue&type=script&lang=js& (http://localhost:8080//js/app.js:87383:62)
```

### Additional Information

None

**Comment by grantholle** [comment]
Extending essentials, like the default theme does, seems to work ok.

```js
import defaultTheme from '@laraform/laraform/src/themes/default/essentials'

export default utils.extendTheme(defaultTheme, {
...
```

**Comment by laraform** [comment]
It seems like you are including trix multiple times:
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "trix-toolbar" has already been used with this registry
```

The reason why essentials does not throw error is because Trix is not among essential elements. 

I'd recommend double checking that you are not including Trix anywhere else in your project.

**Comment by tanthammar** [comment]
I have the same problem.
There is something with the extending the theme that loads trix twice.
If I remove the custom theme I get no errors.

resources/laraform/theme/index.js
```js
import extendTheme from '@laraform/laraform/src/utils'
import defaultTheme from '@laraform/laraform/src/themes/default'

import TextElement from './components/elements/TextElement.vue'

export default extendTheme(defaultTheme, {
  classes: {},
    elements: {
      TextElement
  },
  components: {},
  layouts: {},
  grid: {},
})
```
app.js
```js
import Vue from 'vue'

import Laraform from '@laraform/laraform' // <- Premimum package
import QuasarTheme from '../laraform/theme'

Laraform.theme('quasar-theme', QuasarTheme)

Laraform.config({
  theme: 'quasar-theme',
  endpoints: {
    process: '/laraform/process',
    // Only required for full version
    elements: {
      trix: {
        attachment: '/laraform/trix-attachment'
      }
    },
    validators: {
      active_url: '/laraform/validator/active_url',
      exists: '/laraform/validator/exists',
      unique: '/laraform/validator/unique',
    },
  }
})

Vue.use(Laraform)
```

TextElement.vue
```js
<template>
  <div class="my-text-element">
    <label
      :for="name"
    >{{ label }}</label>

    <input
      v-model="model"
      :type="inputType"
    />
  </div>
</template>

<script>
  import TextElement from '@laraform/laraform/src/components/elements/TextElement'

  export default {
    mixins: [TextElement]
  }
</script>
``` 

Error:
````
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "trix-toolbar" has already been used with this registry
````

**Comment by grantholle** [comment]
I'm not including Trix anywhere or using it anywhere.

**Comment by tanthammar** [comment]
Me neither.

**Comment by laraform** [comment]
Ok so the problem is that the compiled .js file in `dist` already includes Trix and it conflicts with the Trix library that we import in the theme. A quick workaround is to import `@laraform/laraform/src` instead of `@larafom/laraform` until the fix is released.

**Comment by mike2410** [comment]
Importing src seems to work.
Note that you had a typo there @larafo**r**m/laraform/src that just tripped me up ;-) Maybe document this somewhere? @laraform

**Comment by laraform** [comment]
Thanks @mike2410, I've updated the comment as well as the [docs](https://laraform.io/docs/1.x/how-tos/creating-theme#registering-theme-file).
